# Generated by Django 5.0.1 on 2024-02-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_type',
            new_name='type',
        ),
    ]
